### ISSUE TITLE
vendoring @types/node

### ISSUE THREAD

**Issue by zeke** [electron/electron-typescript-definitions#19]
The Electron typescript definitions need to include some stuff from node like EventEmitter.

It was suggested during our recent mini-summit that we should just `npm install @types/node` and call it a day, but I'm thinking it would be nicer if instead we bundle the node definitions right into the generated `electron.d.ts` file. That way when we publish `electron.d.ts` as an Electron release artifact it will be complete and self-contained.

This approach would make things easier (and safer) in a number of ways:

- pulling the new `electron.d.ts` file into `electron-prebuilt` when a new Electron is published will be easier than making it prebuilt's responsibility to figure out which `@types/node` to be using.
- same goes for pushing the new `electron.d.ts` to DT/DT. No extra footwork, just a single file.
- no risk of dependency installation failures when people `npm install electron`
- no direct reliance on npm scoped packages

To make sure we're bundling the right version of node, we can line up electron<->node version numbers using this file: https://atom.io/download/electron/index.json

```json
{
  "version": "1.6.4",
  "date": "2017-03-22",
  "node": "7.4.0",
  "v8": "5.6.326.50",
  "uv": "1.10.1",
  "zlib": "1.2.8",
  "openssl": "1.0.2j",
  "modules": "53",
  "chrome": "56.0.2924.87"
}
```

**Comment by zeke** [comment]
cc @miniak @felixrieseberg @MarshallOfSound does this sound reasonable?

**Comment by felixrieseberg** [comment]
I'm okay with this, if it makes things easier. I'm usually against "let's copy dependencies in" approaches, but I think the downside is small enough that you shouldn't have to sweat it :wink:

**Comment by MarshallOfSound** [comment]
Normally I would be against this kind of thing, but in this case, I think it makes sense.  Technically the user isn't using Electron and Node.JS.  They are using Electron which wraps / includes Node.JS so it semantically makes sense for our typings to include the Node.JS typings 👍

**Comment by zeke** [comment]
A change of heart: https://github.com/electron-userland/electron-prebuilt/pull/249

**Comment by zeke** [comment]
We ended up shipping with `@types/node` bundled as a dependency of electron-prebuilt: https://github.com/electron-userland/electron-prebuilt/pull/249
