### ISSUE TITLE
Enum types are generated as string

### ISSUE THREAD

**Issue by miniak** [electron/electron-typescript-definitions#20]
Example

```
interface DownloadItem extends EventEmitter {
    ...
    public getState(): string;
    ...
}
```

should be generated as:

```
interface DownloadItem extends EventEmitter {
    ...
    public getState(): 'progressing' | 'completed' | 'cancelled' | 'interrupted';
    ...
}
```

or

```
type DownloadItemState = 'progressing' | 'completed' | 'cancelled' | 'interrupted';

interface DownloadItem extends EventEmitter {
    ...
    public getState(): DownloadItemState;
    ...
}
```

Without this fix I don't consider the generated typings to be a good enough replacement for the manually created ones as it decreases type safety.

**Comment by MarshallOfSound** [comment]
Hmm, these values are documented correctly.  Will dig into why the docs linter isn't picking them out

https://github.com/electron/electron/blob/master/docs/api/download-item.md#downloaditemgetstate
