### ISSUE TITLE
IpcMain listener type needs to be specified

### ISSUE THREAD

**Issue by miniak** [electron/electron-typescript-definitions#27]
The existing typings on DefinitelyTyped define this:

```
// https://github.com/electron/electron/blob/master/docs/api/ipc-main.md

/**
 * The ipcMain module handles asynchronous and synchronous messages
 * sent from a renderer process (web page).
 * Messages sent from a renderer will be emitted to this module.
 */
interface IpcMain extends NodeJS.EventEmitter {
    addListener(channel: string, listener: IpcMainEventListener): this;
    on(channel: string, listener: IpcMainEventListener): this;
    once(channel: string, listener: IpcMainEventListener): this;
    removeListener(channel: string, listener: IpcMainEventListener): this;
    removeAllListeners(channel?: string): this;
}

type IpcMainEventListener = (event: IpcMainEvent, ...args: any[]) => void;

interface IpcMainEvent {
    /**
      * Set this to the value to be returned in a synchronous message.
      */
    returnValue?: any;
    /**
     * Returns the webContents that sent the message, you can call sender.send
     * to reply to the asynchronous message.
     */
    sender: WebContents;
}
```

which allows this code to be written:

```
ipcMain.on('hello', (event) => {
    event.sender.send('world!');
});
```

Related to: https://github.com/electron/electron-typescript-definitions/issues/29

**Comment by MarshallOfSound** [comment]
If this is documented correctly in the Electron markdown files this can be auto generated.  We just need to change `on`, `once` Etc. in the docs to have an event type of `IpcMainEvent` and document that type as a structure

**Comment by GitFlip** [comment]
Any status on this? I get the `[ts] Parameter 'event' implicitly has an 'any' type.`, but as far as I can tell there is no Type yet for the event and so I must explicitly use the `any` which I'd prefer not to do.

**Comment by Mike-Dax** [comment]
I might be getting confused - but the markdown here:

https://github.com/electron/electron/blob/master/docs/api/ipc-main.md

...suggests the type of the listener's event is `IpcMainEvent`, but in the typescript definitions imported from the electron package I can only find `IpcMessageEvent`.

```
  interface IpcMessageEvent extends Event {
    channel: string;
    args: any[];
  }
```

Does the IpcMainEvent type exist / contain anything other than the contents of IpcMessageEvent?

So @MarshallOfSound I'm relatively sure that means it isn't documented correctly. Should I open a PR to change that markdown file?

**Comment by MarshallOfSound** [comment]
@Mike-Dax We updated the `Event` docs and generation quite recently on master, this issue will be fixed from 6.0 onwards in the generated types.

The next nightly release of `6.0` will have the correct types in, closing this out as we have fixed it in master

**Comment by MarshallOfSound** [comment]
E.g. The IPCMain event docs --> https://github.com/electron/electron/blob/master/docs/api/structures/ipc-main-event.md

**Comment by vladimiry** [comment]
@MarshallOfSound 

> E.g. The IPCMain event docs --> https://github.com/electron/electron/blob/master/docs/api/structures/ipc-main-event.md

What is the difference between calling [event.sender.send](https://electronjs.org/docs/api/ipc-main#sending-messages) / [send](https://electronjs.org/docs/api/web-contents#contentssendchannel-arg1-arg2-) and [event.reply](https://github.com/electron/electron/blob/3b74837020b15a6c7ef74677f78bcab01a7466a9/docs/api/ipc-main.md)?
