### ISSUE TITLE
Cannot find type definition file for 'node'

### ISSUE THREAD

**Issue by zeke** [electron/electron-typescript-definitions#43]
Related to #39 

In #41, @MarshallOfSound updated the linter to run `tsc` checks on the generated `electron.d.ts` file. For convenience, here's the invocation:

```
cd electron/electron
npm i -D electron-typescript-definitions@latest
electron-docs-linter docs --outfile=electron-api.json --version=1.7.0
electron-typescript-definitions --in=electron-api.json --out=electron.d.ts
```

As of `electron-typescript-definitions@1.2.2`, I see the following errors (with duplicates removed) when running against electron/electron master:

```
index.d.ts(6,1): error TS2688: Cannot find type definition file for 'node'.

index.d.ts(1101,30): error TS2304: Cannot find name 'Buffer'.
index.d.ts(7670,23): error TS2307: Cannot find module 'fs'.
index.d.ts(7679,29): error TS2304: Cannot find name 'EventEmitter'.
test/main.ts(28,23): error TS2307: Cannot find module 'path'.
test/main.ts(39,7): error TS2304: Cannot find name 'process'.
test/main.ts(65,32): error TS2304: Cannot find name '__dirname'.
test/main.ts(98,27): error TS2304: Cannot find name 'Buffer'.
test/renderer.ts(38,43): error TS7006: Parameter 'err' implicitly has an 'any' type.
test/renderer.ts(65,12): error TS2304: Cannot find name 'require'.
test/renderer.ts(115,23): error TS2304: Cannot find name 'require'.
test/renderer.ts(117,68): error TS7006: Parameter 'error' implicitly has an 'any' type.
test/renderer.ts(117,75): error TS7006: Parameter 'sources' implicitly has an 'any' type.
test/renderer.ts(188,1): error TS2304: Cannot find name 'process'.
test/renderer.ts(189,2): error TS2304: Cannot find name 'global'.
test/renderer.ts(190,2): error TS2304: Cannot find name 'global'.
test/renderer.ts(247,2): error TS2304: Cannot find name 'require'.
```

@felixrieseberg @MarshallOfSound @poiru what do you think would be the best way to inline what we need from `node.d.ts`? I assume it's more nuanced than just concatenating the two files...

**Comment by zeke** [comment]
cc @shiftkey

**Comment by shiftkey** [comment]
@zeke

> I see the following errors (with duplicates removed) when running against electron/electron master:

I'm still wrapping my head around how the tooling works - what's the easiest way to test it out against `electron/electron` master so I can see this same problem

**Comment by shiftkey** [comment]
@zeke oops, should have read the first code snippet

**Comment by MarshallOfSound** [comment]
@zeke Easy fix is to make `@types/node` a dependency of `electron/electron` (not the prebuilt but the source repo).  In the real world people will have to install `@types/node` themselves

**Comment by zeke** [comment]
The rationale for inline the node definitions is outline here: https://github.com/electron/electron-typescript-definitions/issues/19

**Comment by MarshallOfSound** [comment]
@zeke Are you saying actually pull in the node typings file into our typings file?

**Comment by zeke** [comment]
Posted without seeing your comment. `cd electron && npm i -D @types/node` is okay by me if that'll do the trick.

**Comment by shiftkey** [comment]
@zeke the error comes up because of this line at the start of the generated file

```ts
/// <reference types="node" />
```

This tells `tsc` to include the declarations from `@types/node` - and as @MarshallOfSound suggests this is something you'll need for doing any sort of Typescript + Node work. So unless it really gets in the way I'd just add it as a devDependency (that makes my setup happy).

**Comment by zeke** [comment]
Ok. So this works in the sense that it produces a file and doesn't throw any errors:

```
cd electron/electron
npm i -D @types/node
electron-typescript-definitions --in=electron-api.json --out=electron.d.ts
```

> In the real world people will have to install `@types/node` themselves

What will happen if they don't?

If the answer is "something annoying", would adding `@types/node` as a dependency (not devDependency) of `electron-prebuilt` solve the problem?

**Comment by MarshallOfSound** [comment]
@zeke It would solve the problem but it would add a useless dependency for people who don't use typescript.  Idm really, however you want to solve it 👍

**Comment by shiftkey** [comment]
> What will happen if they don't?

Anything node-related doesn't light up, and `tsc` generates errors.

For example:

![](https://cloud.githubusercontent.com/assets/359239/25934621/51cc84f4-3662-11e7-810c-401bef7c8683.png)

Compared to with `@types/node`:

![](https://cloud.githubusercontent.com/assets/359239/25934626/5b27335a-3662-11e7-82ba-3a4a1e8f3d62.png)

Given this is for Typescript-specific consumers, I wouldn't force this on everyone.

**Comment by zeke** [comment]
So what happens if you're using Visual Studio Code, not writing TypeScript, and working on a project that depends on `electron`? Would you see errors?

**Comment by zeke** [comment]
Aside from it ending up being an unused dependency for many electron users, is there any other reason _not_ to add `@types/node` as a dependency of the `electron` package?

**Comment by MarshallOfSound** [comment]
@zeke I don't believe so, pretty sure it would give typings correctly for everything as VSCode has bundled node.js typings (or at least appears to).  I.e. type prompting node.js imports works out of the box

**Comment by MarshallOfSound** [comment]
> Aside from it ending up being an unused dependency for many electron users, is there any other reason not to add @types/node as a dependency of the electron package?

Nope, none at all 👍

**Comment by shiftkey** [comment]
VSCode is able to use those declarations to infer a lot about the code and give you an intellisense-esque experience, but it won't enforce these constraints on your code.
