### ISSUE TITLE
clarify App.makeSingleInstance signature

### ISSUE THREAD

**Issue by shiftkey** [electron/electron-typescript-definitions#47]
The generated signature for [app.makeSingleInstance](https://electron.atom.io/docs/api/app/#appmakesingleinstancecallback) looks like this:

```ts
makeSingleInstance(callback: (argv?: string[], workingDirectory?: string) => void): void;
```

There's a couple of things that I'd like to clarify:

 - having `argv` and `workingDirectory` optional here suggests we need to validate they're not undefined. Is that accurate?
 - The return type of this method should be `boolean` as per the docs:

> This method returns `false` if your process is the primary instance of the application and your app should continue loading. And returns `true` if your process has sent its parameters to another instance, and you should immediately quit.

**Comment by MarshallOfSound** [comment]
Will track the first thing (optional params) in #48 and the second thing I just put a PR up to Electron to fix.

**Comment by MarshallOfSound** [comment]
https://github.com/electron/electron/pull/9432/files
