### ISSUE TITLE
All event listener parameters are incorrectly optional

### ISSUE THREAD

**Issue by poiru** [electron/electron-typescript-definitions#48]
For example:

```ts
on(event: 'login', listener: (event?: Event,
                              webContents?: WebContents,
                              request?: Request,
                              authInfo?: AuthInfo,
                              callback?: (username?: string, password?: string) => void) => void): this;
```

This causes a lot of `error TS2532: Object is possibly 'undefined'.` errors in our codebase.

Compare this with the [@types/electron](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cf735753cf6ad4b75c30c45558a8a44daccb19f6/types/electron/index.d.ts#L170-L174) definitions:

```ts
on(event: 'login', listener: (event: Event,
  webContents: WebContents,
  request: LoginRequest,
  authInfo: LoginAuthInfo,
  callback: (username: string, password: string) => void
) => void): this;
```

cc @zeke @MarshallOfSound

**Comment by poiru** [comment]
cc @zeke @MarshallOfSound

**Comment by MarshallOfSound** [comment]
@poiru What rule / config is throwing that error, we should add it to our tests to get failing cases 👍

**Comment by poiru** [comment]
@MarshallOfSound `"strictNullChecks": true`. I suggest also using `"noImplicitAny": true`.
