### ISSUE TITLE
electron version comment regression

### ISSUE THREAD

**Issue by zeke** [electron/electron-typescript-definitions#5]
<img width="358" alt="screen shot 2017-03-23 at 1 30 55 pm" src="https://cloud.githubusercontent.com/assets/2289/24269045/047dbfa8-0fcd-11e7-9731-36384c6d8b5e.png">

https://github.com/electron/electron-definitelytyped/blob/3aef1aedbb2d4dede32696b2a59a08f017c223fa/index.js#L19

**Comment by MarshallOfSound** [comment]
Electron version is fetched here

https://github.com/electron/electron-definitelytyped/blob/master/index.js#L56

Perhaps the structure of the JSON file changed a bit?

**Comment by zeke** [comment]
@MarshallOfSound hot-fixed this to master. 🙇
