### ISSUE TITLE
Shouldn't electron declared as a module instead of an namespace?

### ISSUE THREAD

**Issue by mode777** [electron/electron-typescript-definitions#59]
I got these typings via the electron npm package. I noticed, that electron is declared as an ambient module with

```ts
declare namespace electron {
...
}
```

The typings kind of work but are a bit awkward to use because you have to treat electron as a global object.
However it's actually a module you import with
```js
const electron = require('electron');
// or in typescript
import * as electron from 'electron';
```

So the definitions should declare a module too, like this:
```ts
declate module electron {
...
}
```
at least node and most other packages do it like that. Is there any reason why it shouldn't be declared as a module?

**Comment by MarshallOfSound** [comment]
See #55
