### ISSUE TITLE
Definitions are inconsistent with documentation

### ISSUE THREAD

**Issue by 3n-mb** [electron/electron-typescript-definitions#66]
#### Location for this issue
I assume that electron-typescript-definitions is used to generate `electron.d.ts`. So I place issue here. If it needs redirection, let me now. I'd love to just do a PR, but, with generation, it is not clear where to go.

#### Settings, were it has been observed
It is a fresh install from npm, electron 1.6.11. File `electron.d.ts`, included with package in my `npm_modules`.

#### Issue 1:
Lines 2929-2945, definition of `registerFileProtocol(...)`.
Doc lines say (as well as docs on site),
```
     *  .... To handle
     * the request, the callback should be called with either the file's path or an
     * object that has a path property, e.g. callback(filePath) or callback({path:
     * filePath}). When callback is called with nothing, a number, or an object that
     * has an error property, the request will fail with the error number you
     * specified. 
```
but definition itself is
```
    registerFileProtocol(scheme: string, handler: (request: RegisterFileProtocolRequest, callback: (filePath?: string) => void) => void, completion?: (error: Error) => void): void;
```
`callback`'s function definition has arguments `filePath?: string`, but it should also take in values that will make request fail, i.e. `filePath?: string | number | ...`

#### Issue 2:
Lines 2922-2928, definition for `registerBufferProtocol(...)`.
Doc lines say (as well as docs on site),
```
     *  ....  The usage
     * is the same with registerFileProtocol, except that the callback should be called
     * with either a Buffer object or an object that has the data, mimeType, and
     * charset properties. Example:
     */
```
but definition itself is
```
    registerBufferProtocol(scheme: string, handler: (request: RegisterBufferProtocolRequest, callback: (buffer?: Buffer | MimeTypedBuffer) => void) => void, completion?: (error: Error) => void): void;
```
misses types for `buffer` argument in `callback`, that will make request to fail. It should be at least `buffer?: Buffer | MimeTypedBuffer | number`, which I know runs properly.

By the way, it seems that an *Example:* part of the doc line is chopped off.

#### Issue 3:
Lines 2917-2921, definition for `isProtocolHandled(...)`.
Doc lines say,
```
    /**
     * The callback will be called with a boolean that indicates whether there is
     * already a handler for scheme.
     */
```
but definition itself is
```
isProtocolHandled(scheme: string, callback: (error: Error) => void): void;
```
where callback argument should be `callback: (isHandled: boolean) => void`.

**Comment by MarshallOfSound** [comment]
All three are valid issues, the key thing to understand here is the typescript file is generated from the **structured** parts of the documentation, so anything in a comment or in a paragraph won't be able to be interpreted.

So for instance for your first issue the definition is found from the structured bit here https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolregisterfileprotocolscheme-handler-completion.

If the structured bit is either incomplete or wrong a PR to fix it will also fix the definitions.

Same with the other 2 issues you mentioned, fixing the structured bit of the documentation will fix the definitions 👍

**Comment by 3n-mb** [comment]
@MarshallOfSound you are saying that I should PR change to doc's '.md' file?

**Comment by 3n-mb** [comment]
I did [PR](https://github.com/electron/electron/pull/10090) to docs.

Can you comment on using types like `{path:string}` in structured part of docs. Will it work, i.e. are `{`'s fine for auto-generation?

**Comment by MarshallOfSound** [comment]
@3n-mb You can't use that style of types in the structured parts of the docs, gave a better comment on your PR.  Thanks for putting the time in to fix this 👍

**Comment by 3n-mb** [comment]
You are very welcome. Thank you for doing this.
I am closing this issue, as everything else goes in mentioned PR.
