### ISSUE TITLE
Typings vs docs

### ISSUE THREAD

**Issue by wasd171** [electron/electron-typescript-definitions#67]
Hi!

I have a question. In the docs for [session.clearStorageData](https://github.com/electron/electron/blob/master/docs/api/session.md#sesclearstoragedataoptions-callback), all properties of `options` are optional. But `electron.d.ts` has
```
interface ClearStorageDataOptions {
    /**
     * Should follow window.location.origin’s representation scheme://host:port.
     */
    origin: string;
    /**
     * The types of storages to clear, can contain: appcache, cookies, filesystem,
     * indexdb, localstorage, shadercache, websql, serviceworkers
     */
    storages: string[];
    /**
     * The types of quotas to clear, can contain: temporary, persistent, syncable.
     */
    quotas: string[];
}
```
Which version is correct?

**Comment by MarshallOfSound** [comment]
The docs, the definitions will be correct in more recent releases of Electron.  The docs were only fixed recently.

https://github.com/electron/electron/commit/de066b8d1384fb89546295d0e53f0c3c8cda79ff
