### ISSUE TITLE
WebRequest: filter argument is optional but not in electron.d.ts

### ISSUE THREAD

**Issue by bpasero** [electron/electron-typescript-definitions#75]
Refs: https://github.com/electron/electron/issues/10448

It looks like all the WebRequest definitions are not declaring the first filter argument as optional. The [documentation](https://github.com/electron/electron/blob/3ec7900e6e72aeb2c273f47a97498a093580da94/docs/api/web-request.md#webrequestonbeforerequestfilter-listener) looks like this:

`webRequest.onBeforeRequest([filter, ]listener)`

And the resulting electron.d.ts entry is:

```typescript
onBeforeRequest(filter: OnBeforeRequestFilter, listener: (details: OnBeforeRequestDetails, callback: (response: Response) => void) => void): void;
```

It looks like this should get generated though:

```typescript
onBeforeRequest(listener: (details: OnBeforeRequestDetails, callback: (response: Response) => void) => void): void;
onBeforeRequest(filter: OnBeforeRequestFilter, listener: (details: OnBeforeRequestDetails, callback: (response: Response) => void) => void): void;
```

**Comment by MarshallOfSound** [comment]
Looks like the docs parser is at fault here

```js
{ name: 'onBeforeRequest',
  signature: '([filter, ]listener)',
  description: 'The listener will be called with listener(details, callback) when a request is about to occur. The uploadData is an array of UploadData objects. The callback has to be called with an response object.',
  parameters:
   [ { name: 'filter',
       type: 'Object',
       collection: false,
       required: true,
       properties: [Object] },
     { name: 'listener',
       type: 'Function',
       collection: false,
       required: true,
       parameters: [Object] } ] }
```

The argument is not declared as optional in the JSON output

**Comment by MarshallOfSound** [comment]
Ah, we need to declare the `filter` argument as "(optional)" in the description of that parameter 👍
