### ISSUE TITLE
remote does not identify BrowserWindow correctly

### ISSUE THREAD

**Issue by Acidic9** [electron/electron-typescript-definitions#97]
I'm trying to use the remote module in electron. You would require it in regular JS like so:

    const {BrowserWindow} = require('electron').remote

and in TypeScript, I am trying to import it with:

    import {remote} from 'electron'

then in my TypeScript documnet I use it with

    const win: remote.BrowserWindow = new remote.BrowserWindow({ ... })

But I get an error at the variable type declaration (`win: remote.BrowserWindow`) saying `[ts] Cannot find namespace 'remote'.`

---

Is this something I am doing wrong, or is the electron TypeScript definition file incorrect?

**Comment by ctexxx** [comment]
me too

**Comment by MarshallOfSound** [comment]
`remote` is not a namespace, that is invalid Typescript.

You want this

```js
import { BrowserWindow, remote } from 'electron'

// BrowserWindow is just the type import, remote.BrowserWindow is the value
const win: BrowserWindow = new remote.BrowserWindow({ .. })
```
