### ISSUE TITLE
Can no longer use electron definition in VS Code with jsconfig

### ISSUE THREAD

**Issue by Bigmacbook** [electron/electron-typescript-definitions#98]
I don't want electron in my node_modules so I use jsconfig.json file to get definition files, but it no longer works. VS Code use to grab the definition files with jsconfig.

```
{
    "typeAcquisition": {
        "include": [
            "node",
            "electron"
        ]
    }
} 
```

**Comment by MarshallOfSound** [comment]
@Bigmacbook I do not know how jsconfig works but I'd suggest raising this issue with the VS Code team.  All we do is generate definition files and include them in our releases, nothing special beyond that.
